#!/usr/bin/env bash

echo "Creating tun"
ip tuntap add mode tun dev ${1}

echo "Bringing up link"
ip link set ${1} up

echo "Setting IP"
ip addr add 10.0.0.2/24 dev ${1}

echo "Setting default route"
#ip route add 10.0.0.1/32 via 192.168.1.203 dev wlp2s0;
ip route add 8.8.8.8/32 via 10.0.0.1 dev ${1}
ip route add 93.184.216.34/32 via 10.0.0.1 dev ${1}
ip route add 151.101.129.140/32 via 10.0.0.1 dev ${1}
ip route add 151.101.65.140/32 via 10.0.0.1 dev ${1}
ip route add 151.101.193.140/32 via 10.0.0.1 dev ${1}
ip route add 151.101.1.140/32 via 10.0.0.1 dev ${1}
#ip route add 0.0.0.0/0 via 10.0.0.1 dev ${1}

#echo "Enabling IPTables Routing"
#iptables -P INPUT ACCEPT
#iptables -P OUTPUT ACCEPT
#iptables -P FORWARD ACCEPT
#iptables -t nat -A POSTROUTING -s "10.0.0.1/32" -o "wlp2s0" -j SNAT --to "192.168.1.1"
