#!/usr/bin/env bash

echo "Creating tun"
ip tuntap add mode tun dev ${1}

echo "Bringing up link"
ip link set ${1} up

echo "Setting IP"
ip addr add 10.0.0.1/24 dev ${1}

echo "Setting default route"
ip route add 10.0.0.1/32 via 192.168.1.203 dev wlp2s0;
ip route add 8.8.8.8/32 via 10.0.0.1 dev ${1}
